using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using Wayfinder.Models.ServiceDesign;

namespace UmbracoPrism.Core.Services.ServiceDesign;

/// <summary>
/// Default <see cref="IServiceRequestFileStorage"/> — writes uploaded files to disk under
/// <c>App_Data/prism-workflow-uploads/{instanceId}/</c> (gitignored, host-local). InstanceId
/// alone is enough to namespace storage — it's already a globally unique id generated by the
/// engine, and ownership is enforced separately (by the engine's own instance-access check)
/// rather than by this storage layout. The stored filename is always a generated GUID, never
/// the visitor's original filename — <see cref="ServiceRequestFileReference.StorageKey"/> is the only
/// thing trusted to build a path from, and every path built from it is verified to stay under
/// the storage root before use.
/// </summary>
public sealed class DiskServiceRequestFileStorage : IServiceRequestFileStorage
{
    private readonly string _root;

    public DiskServiceRequestFileStorage(IHostEnvironment environment)
    {
        _root = Path.GetFullPath(Path.Combine(environment.ContentRootPath, "App_Data", "prism-workflow-uploads"));
    }

    public async Task<ServiceRequestFileReference> SaveAsync(
        string instanceId,
        string fieldKey,
        IFormFile file,
        CancellationToken cancellationToken = default)
    {
        var safeInstanceId = SanitizePathSegment(instanceId);
        var directory = Path.Combine(_root, safeInstanceId);
        Directory.CreateDirectory(directory);

        var storageFileName = $"{Guid.NewGuid():N}{Path.GetExtension(file.FileName)}";
        var storageKey = $"{safeInstanceId}/{storageFileName}";

        await using (var destination = File.Create(Path.Combine(directory, storageFileName)))
        {
            await file.CopyToAsync(destination, cancellationToken);
        }

        return new ServiceRequestFileReference
        {
            StorageKey = storageKey,
            OriginalFileName = Path.GetFileName(file.FileName),
            ContentType = file.ContentType,
            SizeBytes = file.Length
        };
    }

    public Task<Stream> OpenReadAsync(ServiceRequestFileReference reference, CancellationToken cancellationToken = default)
    {
        Stream stream = File.OpenRead(ResolveFullPath(reference.StorageKey));
        return Task.FromResult(stream);
    }

    private string ResolveFullPath(string storageKey)
    {
        var fullPath = Path.GetFullPath(Path.Combine(_root, storageKey));
        if (!fullPath.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Storage key '{storageKey}' resolves outside the storage root.");
        }

        return fullPath;
    }

    /// <summary>
    /// Strips path separators and reserved names from a path segment so it can never introduce
    /// an extra directory level (traversal via "..", or an absolute-path escape) — every
    /// segment used to build a file path on disk goes through this first.
    /// </summary>
    private static string SanitizePathSegment(string value)
    {
        if (string.IsNullOrWhiteSpace(value) || value is "." or "..")
        {
            return Guid.NewGuid().ToString("N");
        }

        var invalidChars = Path.GetInvalidFileNameChars();
        return new string(value.Select(c => invalidChars.Contains(c) ? '_' : c).ToArray());
    }
}
